version: '{build}'

nuget:
  disable_publish_on_pr: true

configuration: Release

environment:
   # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
# - dotnet --info
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build --no-restore -c %CONFIGURATION%

test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
    - DoNotRunOnAppVeyor

after_test:
- dotnet pack --no-build --no-restore -c %CONFIGURATION%

artifacts:
- path: build\**\*.nupkg
  name: NuGet

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: KNFSKb7s+3+79G+FOMmubE+llHdsyV+3ApSqqgrbia5DM4RCzKDEIXaQGPqip9bf
  skip_symbols: true
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true
